package com.example.CS499_Capstone

object SeedData {

    val inventoryItems: List<InventoryItemEntity> = listOf(
        InventoryItemEntity(name = "Nitrile Gloves", quantity = 120),
        InventoryItemEntity(name = "Latex Gloves", quantity = 75),
        InventoryItemEntity(name = "Surgical Masks", quantity = 200),
        InventoryItemEntity(name = "Face Shields", quantity = 35),
        InventoryItemEntity(name = "Protective Gowns", quantity = 50),
        InventoryItemEntity(name = "Hand Sanitizer", quantity = 80),
        InventoryItemEntity(name = "Disinfectant Wipes", quantity = 65),
        InventoryItemEntity(name = "Surface Disinfectant Spray", quantity = 40),
        InventoryItemEntity(name = "Paper Towels", quantity = 90),
        InventoryItemEntity(name = "Tissues", quantity = 55),

        InventoryItemEntity(name = "Gauze Pads", quantity = 150),
        InventoryItemEntity(name = "Cotton Rolls", quantity = 100),
        InventoryItemEntity(name = "Cotton Swabs", quantity = 125),
        InventoryItemEntity(name = "Bandages", quantity = 85),
        InventoryItemEntity(name = "Medical Tape", quantity = 45),
        InventoryItemEntity(name = "Tongue Depressors", quantity = 110),
        InventoryItemEntity(name = "Disposable Cups", quantity = 180),
        InventoryItemEntity(name = "Patient Bibs", quantity = 140),
        InventoryItemEntity(name = "Tray Covers", quantity = 160),
        InventoryItemEntity(name = "Barrier Film", quantity = 70),

        InventoryItemEntity(name = "Syringe Tips", quantity = 95),
        InventoryItemEntity(name = "Air Water Syringe Sleeves", quantity = 130),
        InventoryItemEntity(name = "Saliva Ejectors", quantity = 115),
        InventoryItemEntity(name = "High Volume Evacuation Tips", quantity = 90),
        InventoryItemEntity(name = "Dental Mirrors", quantity = 25),
        InventoryItemEntity(name = "Explorers", quantity = 20),
        InventoryItemEntity(name = "Cotton Pliers", quantity = 18),
        InventoryItemEntity(name = "Scalers", quantity = 22),
        InventoryItemEntity(name = "Curettes", quantity = 19),
        InventoryItemEntity(name = "Probe Instruments", quantity = 24),

        InventoryItemEntity(name = "Prophy Paste", quantity = 60),
        InventoryItemEntity(name = "Prophy Angles", quantity = 100),
        InventoryItemEntity(name = "Fluoride Varnish", quantity = 45),
        InventoryItemEntity(name = "Fluoride Trays", quantity = 70),
        InventoryItemEntity(name = "Dental Floss", quantity = 95),
        InventoryItemEntity(name = "Toothbrushes", quantity = 150),
        InventoryItemEntity(name = "Travel Toothpaste", quantity = 130),
        InventoryItemEntity(name = "Mouthwash Samples", quantity = 85),
        InventoryItemEntity(name = "Interdental Brushes", quantity = 65),
        InventoryItemEntity(name = "Plaque Disclosing Tablets", quantity = 40),

        InventoryItemEntity(name = "Composite Resin", quantity = 32),
        InventoryItemEntity(name = "Bonding Agent", quantity = 28),
        InventoryItemEntity(name = "Etch Gel", quantity = 35),
        InventoryItemEntity(name = "Microbrushes", quantity = 120),
        InventoryItemEntity(name = "Mixing Pads", quantity = 55),
        InventoryItemEntity(name = "Applicator Tips", quantity = 100),
        InventoryItemEntity(name = "Matrix Bands", quantity = 75),
        InventoryItemEntity(name = "Wedges", quantity = 90),
        InventoryItemEntity(name = "Curing Light Sleeves", quantity = 80),
        InventoryItemEntity(name = "Articulating Paper", quantity = 50),

        InventoryItemEntity(name = "Impression Material", quantity = 30),
        InventoryItemEntity(name = "Impression Trays", quantity = 42),
        InventoryItemEntity(name = "Alginate", quantity = 38),
        InventoryItemEntity(name = "Bite Registration Material", quantity = 26),
        InventoryItemEntity(name = "Temporary Cement", quantity = 24),
        InventoryItemEntity(name = "Permanent Cement", quantity = 20),
        InventoryItemEntity(name = "Crown Forms", quantity = 34),
        InventoryItemEntity(name = "Temporary Crown Material", quantity = 25),
        InventoryItemEntity(name = "Retraction Cord", quantity = 18),
        InventoryItemEntity(name = "Hemostatic Solution", quantity = 16),

        InventoryItemEntity(name = "Anesthetic Carpules", quantity = 100),
        InventoryItemEntity(name = "Topical Anesthetic", quantity = 45),
        InventoryItemEntity(name = "Needles Short", quantity = 85),
        InventoryItemEntity(name = "Needles Long", quantity = 70),
        InventoryItemEntity(name = "Syringe Covers", quantity = 95),
        InventoryItemEntity(name = "Sharps Containers", quantity = 12),
        InventoryItemEntity(name = "Alcohol Prep Pads", quantity = 140),
        InventoryItemEntity(name = "Sterile Water", quantity = 30),
        InventoryItemEntity(name = "Irrigation Syringes", quantity = 55),
        InventoryItemEntity(name = "Endodontic Files", quantity = 40),

        InventoryItemEntity(name = "Sterilization Pouches", quantity = 160),
        InventoryItemEntity(name = "Autoclave Tape", quantity = 35),
        InventoryItemEntity(name = "Sterilization Indicators", quantity = 90),
        InventoryItemEntity(name = "Instrument Cassettes", quantity = 15),
        InventoryItemEntity(name = "Ultrasonic Cleaning Solution", quantity = 20),
        InventoryItemEntity(name = "Instrument Lubricant", quantity = 18),
        InventoryItemEntity(name = "Disposable Headrest Covers", quantity = 100),
        InventoryItemEntity(name = "Chair Sleeves", quantity = 85),
        InventoryItemEntity(name = "Light Handle Covers", quantity = 95),
        InventoryItemEntity(name = "X-Ray Sensor Sleeves", quantity = 110),

        InventoryItemEntity(name = "X-Ray Phosphor Plates", quantity = 25),
        InventoryItemEntity(name = "Lead Aprons", quantity = 6),
        InventoryItemEntity(name = "Bitewing Tabs", quantity = 70),
        InventoryItemEntity(name = "Sensor Holders", quantity = 28),
        InventoryItemEntity(name = "Developer Cleaner", quantity = 10),
        InventoryItemEntity(name = "Printer Paper", quantity = 45),
        InventoryItemEntity(name = "Appointment Cards", quantity = 100),
        InventoryItemEntity(name = "Prescription Pads", quantity = 20),
        InventoryItemEntity(name = "Patient Forms", quantity = 75),
        InventoryItemEntity(name = "Clipboards", quantity = 18),

        InventoryItemEntity(name = "Trash Bags", quantity = 60),
        InventoryItemEntity(name = "Biohazard Bags", quantity = 45),
        InventoryItemEntity(name = "Soap Refills", quantity = 35),
        InventoryItemEntity(name = "Laundry Detergent", quantity = 22),
        InventoryItemEntity(name = "Exam Room Cleaner", quantity = 28),
        InventoryItemEntity(name = "Batteries AA", quantity = 50),
        InventoryItemEntity(name = "Batteries AAA", quantity = 48),
        InventoryItemEntity(name = "Labels", quantity = 80),
        InventoryItemEntity(name = "Storage Bins", quantity = 14),
        InventoryItemEntity(name = "Inventory Tags", quantity = 100)
    )
}