package com.example.CS499_Capstone

object SeedData {

    val inventoryItems: List<InventoryItemEntity> = listOf(
        InventoryItemEntity(name = "Nitrile Gloves", quantity = 120, category = "PPE", lowStockThreshold = 25),
        InventoryItemEntity(name = "Latex Gloves", quantity = 75, category = "PPE", lowStockThreshold = 20),
        InventoryItemEntity(name = "Surgical Masks", quantity = 200, category = "PPE", lowStockThreshold = 50),
        InventoryItemEntity(name = "Face Shields", quantity = 35, category = "PPE", lowStockThreshold = 10),
        InventoryItemEntity(name = "Protective Gowns", quantity = 50, category = "PPE", lowStockThreshold = 15),
        InventoryItemEntity(name = "Hand Sanitizer", quantity = 80, category = "Infection Control", lowStockThreshold = 20),
        InventoryItemEntity(name = "Disinfectant Wipes", quantity = 65, category = "Infection Control", lowStockThreshold = 20),
        InventoryItemEntity(name = "Surface Disinfectant Spray", quantity = 40, category = "Infection Control", lowStockThreshold = 12),
        InventoryItemEntity(name = "Paper Towels", quantity = 90, category = "Office Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Tissues", quantity = 55, category = "Office Supplies", lowStockThreshold = 15),

        InventoryItemEntity(name = "Gauze Pads", quantity = 150, category = "Clinical Supplies", lowStockThreshold = 30),
        InventoryItemEntity(name = "Cotton Rolls", quantity = 100, category = "Clinical Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Cotton Swabs", quantity = 125, category = "Clinical Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Bandages", quantity = 85, category = "Clinical Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Medical Tape", quantity = 45, category = "Clinical Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Tongue Depressors", quantity = 110, category = "Clinical Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Disposable Cups", quantity = 180, category = "Patient Supplies", lowStockThreshold = 40),
        InventoryItemEntity(name = "Patient Bibs", quantity = 140, category = "Patient Supplies", lowStockThreshold = 30),
        InventoryItemEntity(name = "Tray Covers", quantity = 160, category = "Patient Supplies", lowStockThreshold = 35),
        InventoryItemEntity(name = "Barrier Film", quantity = 70, category = "Infection Control", lowStockThreshold = 15),

        InventoryItemEntity(name = "Syringe Tips", quantity = 95, category = "Dental Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Air Water Syringe Sleeves", quantity = 130, category = "Dental Supplies", lowStockThreshold = 30),
        InventoryItemEntity(name = "Saliva Ejectors", quantity = 115, category = "Dental Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "High Volume Evacuation Tips", quantity = 90, category = "Dental Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Dental Mirrors", quantity = 25, category = "Instruments", lowStockThreshold = 5),
        InventoryItemEntity(name = "Explorers", quantity = 20, category = "Instruments", lowStockThreshold = 5),
        InventoryItemEntity(name = "Cotton Pliers", quantity = 18, category = "Instruments", lowStockThreshold = 5),
        InventoryItemEntity(name = "Scalers", quantity = 22, category = "Instruments", lowStockThreshold = 5),
        InventoryItemEntity(name = "Curettes", quantity = 19, category = "Instruments", lowStockThreshold = 5),
        InventoryItemEntity(name = "Probe Instruments", quantity = 24, category = "Instruments", lowStockThreshold = 5),

        InventoryItemEntity(name = "Prophy Paste", quantity = 60, category = "Preventive Care", lowStockThreshold = 15),
        InventoryItemEntity(name = "Prophy Angles", quantity = 100, category = "Preventive Care", lowStockThreshold = 25),
        InventoryItemEntity(name = "Fluoride Varnish", quantity = 45, category = "Preventive Care", lowStockThreshold = 10),
        InventoryItemEntity(name = "Fluoride Trays", quantity = 70, category = "Preventive Care", lowStockThreshold = 15),
        InventoryItemEntity(name = "Dental Floss", quantity = 95, category = "Patient Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Toothbrushes", quantity = 150, category = "Patient Supplies", lowStockThreshold = 40),
        InventoryItemEntity(name = "Travel Toothpaste", quantity = 130, category = "Patient Supplies", lowStockThreshold = 35),
        InventoryItemEntity(name = "Mouthwash Samples", quantity = 85, category = "Patient Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Interdental Brushes", quantity = 65, category = "Patient Supplies", lowStockThreshold = 15),
        InventoryItemEntity(name = "Plaque Disclosing Tablets", quantity = 40, category = "Preventive Care", lowStockThreshold = 10),

        InventoryItemEntity(name = "Composite Resin", quantity = 32, category = "Restorative Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Bonding Agent", quantity = 28, category = "Restorative Supplies", lowStockThreshold = 7),
        InventoryItemEntity(name = "Etch Gel", quantity = 35, category = "Restorative Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Microbrushes", quantity = 120, category = "Restorative Supplies", lowStockThreshold = 30),
        InventoryItemEntity(name = "Mixing Pads", quantity = 55, category = "Restorative Supplies", lowStockThreshold = 15),
        InventoryItemEntity(name = "Applicator Tips", quantity = 100, category = "Restorative Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Matrix Bands", quantity = 75, category = "Restorative Supplies", lowStockThreshold = 15),
        InventoryItemEntity(name = "Wedges", quantity = 90, category = "Restorative Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Curing Light Sleeves", quantity = 80, category = "Restorative Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Articulating Paper", quantity = 50, category = "Restorative Supplies", lowStockThreshold = 12),

        InventoryItemEntity(name = "Impression Material", quantity = 30, category = "Prosthodontic Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Impression Trays", quantity = 42, category = "Prosthodontic Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Alginate", quantity = 38, category = "Prosthodontic Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Bite Registration Material", quantity = 26, category = "Prosthodontic Supplies", lowStockThreshold = 6),
        InventoryItemEntity(name = "Temporary Cement", quantity = 24, category = "Prosthodontic Supplies", lowStockThreshold = 6),
        InventoryItemEntity(name = "Permanent Cement", quantity = 20, category = "Prosthodontic Supplies", lowStockThreshold = 5),
        InventoryItemEntity(name = "Crown Forms", quantity = 34, category = "Prosthodontic Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Temporary Crown Material", quantity = 25, category = "Prosthodontic Supplies", lowStockThreshold = 6),
        InventoryItemEntity(name = "Retraction Cord", quantity = 18, category = "Prosthodontic Supplies", lowStockThreshold = 5),
        InventoryItemEntity(name = "Hemostatic Solution", quantity = 16, category = "Prosthodontic Supplies", lowStockThreshold = 5),

        InventoryItemEntity(name = "Anesthetic Carpules", quantity = 100, category = "Anesthesia", lowStockThreshold = 25),
        InventoryItemEntity(name = "Topical Anesthetic", quantity = 45, category = "Anesthesia", lowStockThreshold = 10),
        InventoryItemEntity(name = "Needles Short", quantity = 85, category = "Anesthesia", lowStockThreshold = 20),
        InventoryItemEntity(name = "Needles Long", quantity = 70, category = "Anesthesia", lowStockThreshold = 15),
        InventoryItemEntity(name = "Syringe Covers", quantity = 95, category = "Anesthesia", lowStockThreshold = 20),
        InventoryItemEntity(name = "Sharps Containers", quantity = 12, category = "Safety", lowStockThreshold = 3),
        InventoryItemEntity(name = "Alcohol Prep Pads", quantity = 140, category = "Clinical Supplies", lowStockThreshold = 35),
        InventoryItemEntity(name = "Sterile Water", quantity = 30, category = "Clinical Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Irrigation Syringes", quantity = 55, category = "Clinical Supplies", lowStockThreshold = 12),
        InventoryItemEntity(name = "Endodontic Files", quantity = 40, category = "Endodontic Supplies", lowStockThreshold = 10),

        InventoryItemEntity(name = "Sterilization Pouches", quantity = 160, category = "Sterilization", lowStockThreshold = 40),
        InventoryItemEntity(name = "Autoclave Tape", quantity = 35, category = "Sterilization", lowStockThreshold = 8),
        InventoryItemEntity(name = "Sterilization Indicators", quantity = 90, category = "Sterilization", lowStockThreshold = 20),
        InventoryItemEntity(name = "Instrument Cassettes", quantity = 15, category = "Sterilization", lowStockThreshold = 4),
        InventoryItemEntity(name = "Ultrasonic Cleaning Solution", quantity = 20, category = "Sterilization", lowStockThreshold = 5),
        InventoryItemEntity(name = "Instrument Lubricant", quantity = 18, category = "Sterilization", lowStockThreshold = 5),
        InventoryItemEntity(name = "Disposable Headrest Covers", quantity = 100, category = "Patient Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Chair Sleeves", quantity = 85, category = "Infection Control", lowStockThreshold = 20),
        InventoryItemEntity(name = "Light Handle Covers", quantity = 95, category = "Infection Control", lowStockThreshold = 20),
        InventoryItemEntity(name = "X-Ray Sensor Sleeves", quantity = 110, category = "Radiology", lowStockThreshold = 25),

        InventoryItemEntity(name = "X-Ray Phosphor Plates", quantity = 25, category = "Radiology", lowStockThreshold = 6),
        InventoryItemEntity(name = "Lead Aprons", quantity = 6, category = "Radiology", lowStockThreshold = 2),
        InventoryItemEntity(name = "Bitewing Tabs", quantity = 70, category = "Radiology", lowStockThreshold = 15),
        InventoryItemEntity(name = "Sensor Holders", quantity = 28, category = "Radiology", lowStockThreshold = 6),
        InventoryItemEntity(name = "Developer Cleaner", quantity = 10, category = "Radiology", lowStockThreshold = 3),
        InventoryItemEntity(name = "Printer Paper", quantity = 45, category = "Office Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Appointment Cards", quantity = 100, category = "Office Supplies", lowStockThreshold = 25),
        InventoryItemEntity(name = "Prescription Pads", quantity = 20, category = "Office Supplies", lowStockThreshold = 5),
        InventoryItemEntity(name = "Patient Forms", quantity = 75, category = "Office Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Clipboards", quantity = 18, category = "Office Supplies", lowStockThreshold = 5),

        InventoryItemEntity(name = "Trash Bags", quantity = 60, category = "Facility Supplies", lowStockThreshold = 15),
        InventoryItemEntity(name = "Biohazard Bags", quantity = 45, category = "Safety", lowStockThreshold = 10),
        InventoryItemEntity(name = "Soap Refills", quantity = 35, category = "Facility Supplies", lowStockThreshold = 8),
        InventoryItemEntity(name = "Laundry Detergent", quantity = 22, category = "Facility Supplies", lowStockThreshold = 5),
        InventoryItemEntity(name = "Exam Room Cleaner", quantity = 28, category = "Facility Supplies", lowStockThreshold = 7),
        InventoryItemEntity(name = "Batteries AA", quantity = 50, category = "Office Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Batteries AAA", quantity = 48, category = "Office Supplies", lowStockThreshold = 10),
        InventoryItemEntity(name = "Labels", quantity = 80, category = "Office Supplies", lowStockThreshold = 20),
        InventoryItemEntity(name = "Storage Bins", quantity = 14, category = "Facility Supplies", lowStockThreshold = 4),
        InventoryItemEntity(name = "Inventory Tags", quantity = 100, category = "Office Supplies", lowStockThreshold = 25)
    )
}